---
- name: Ñreate /etc/apt/keyrings directory
  command:
    cmd: mkdir -p -m 755 /etc/apt/keyrings

- name: download k8s gpg key
  shell: curl -fsSL "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
  register: key_output
  changed_when: false

- name: install k8s gpg key
  shell: echo "{{ key_output.stdout }}" | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add entry to kubernetes.list file
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /'
    create: yes

- name: install required 
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
    loop: "{{ k8s_features }}"

- name: hold kubeadm, kubelet, and kubectl
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ k8s_features }}"

- name: enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Read existing content of /etc/modules-load.d/k8s.conf
  shell: cat /etc/modules-load.d/k8s.conf
  register: existing_content
  ignore_errors: yes

- name: Add kernel modules to k8s.conf if missing
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      {% for module in k8s_kernel_modules %}
      {{ module }}
      {% endfor %}
    create: yes
  when: "'overlay' not in existing_modules_content.stdout or 'br_netfilter' not in existing_modules_content.stdout"

- name: Load required kernel modules
  shell: |
    {% for module in k8s_kernel_modules %}
    modprobe {{ module }}
    {% endfor %}

- name: read existing content of /etc/sysctl.d/k8s.conf
  shell: cat /etc/sysctl.d/k8s.conf
  register: existing_content
  ignore_errors: yes

- name: Configure sysctl settings if missing
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      {% for setting in k8s_sysctl_settings %}
      {{ setting }}
      {% endfor %}
    create: yes
  when: "'net.bridge.bridge-nf-call-iptables = 1' not in existing_sysctl_content.stdout or 'net.bridge.bridge-nf-call-ip6tables = 1' not in existing_sysctl_content.stdout or 'net.ipv4.ip_forward = 1' not in existing_sysctl_content.stdout"

- name: apply sysctl settings
  command:
    cmd: sysctl --system

- name: configure containerd
  shell: |
    sh -c "containerd config default > /etc/containerd/config.toml"
    sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml

- name: restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: restart kubelet service
  systemd:
    name: kubelet
    state: restarted